### ISSUE TITLE
server: concurrent map write

### ISSUE THREAD

**Issue by scbizu** [pyroscope-io/pyroscope#112]
Hihi , we recently see a **concurrent map writes** caused panic in our pyroscope container. 

<details>
<summary>Here is some logs:</summary>

```
{"log":"fatal error: concurrent map writes\n","stream":"stderr","time":"2021-03-09T09:26:01.732337651Z"}
{"log":"\n","stream":"stderr","time":"2021-03-09T09:26:01.736547237Z"}
{"log":"goroutine 791825 [running]:\n","stream":"stderr","time":"2021-03-09T09:26:01.736790096Z"}
{"log":"runtime.throw(0x133a4b6, 0x15)\n","stream":"stderr","time":"2021-03-09T09:26:01.736848125Z"}
{"log":"\u0009runtime/panic.go:1116 +0x72 fp=0xc01c14b9b0 sp=0xc01c14b980 pc=0x438632\n","stream":"stderr","time":"2021-03-09T09:26:01.736892216Z"}
{"log":"runtime.mapassign_fast32(0x1291820, 0xc030538150, 0xc003d3bcd6, 0x40c6bb)\n","stream":"stderr","time":"2021-03-09T09:26:01.737024003Z"}
{"log":"\u0009runtime/map_fast32.go:101 +0x33e fp=0xc01c14b9f0 sp=0xc01c14b9b0 pc=0x41313e\n","stream":"stderr","time":"2021-03-09T09:26:01.737074448Z"}
{"log":"github.com/clarkduvall/hyperloglog.set.Add(...)\n","stream":"stderr","time":"2021-03-09T09:26:01.737119879Z"}
{"log":"\u0009github.com/clarkduvall/hyperloglog@v0.0.0-20171127014514-a0107a5d8004/common.go:21\n","stream":"stderr","time":"2021-03-09T09:26:01.737163863Z"}
{"log":"github.com/clarkduvall/hyperloglog.(*HyperLogLogPlus).Add(0xc000098900, 0x1597720, 0xc0347275c0)\n","stream":"stderr","time":"2021-03-09T09:26:01.737204601Z"}
{"log":"\u0009github.com/clarkduvall/hyperloglog@v0.0.0-20171127014514-a0107a5d8004/hyperloglogplus.go:150 +0x71 fp=0xc01c14ba40 sp=0xc01c14b9f0 pc=0x98a951\n","stream":"stderr","time":"2021-03-09T09:26:01.737246673Z"}
{"log":"github.com/pyroscope-io/pyroscope/pkg/server.(*Controller).ingestHandler(0xc000184ea0, 0x15a1d80, 0xc01ce44ee0, 0xc01dc53d00)\n","stream":"stderr","time":"2021-03-09T09:26:01.73729112Z"}
{"log":"\u0009github.com/pyroscope-io/pyroscope/pkg/server/ingest.go:104 +0x405 fp=0xc01c14bb38 sp=0xc01c14ba40 pc=0x9a0a05\n","stream":"stderr","time":"2021-03-09T09:26:01.737335281Z"}
{"log":"github.com/pyroscope-io/pyroscope/pkg/server.(*Controller).ingestHandler-fm(0x15a1d80, 0xc01ce44ee0, 0xc01dc53d00)\n","stream":"stderr","time":"2021-03-09T09:26:01.737384236Z"}
{"log":"\u0009github.com/pyroscope-io/pyroscope/pkg/server/ingest.go:67 +0x48 fp=0xc01c14bb68 sp=0xc01c14bb38 pc=0x9a26e8\n","stream":"stderr","time":"2021-03-09T09:26:01.737493239Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc000188b40, 0x15a1d80, 0xc01ce44ee0, 0xc01dc53d00)\n","stream":"stderr","time":"2021-03-09T09:26:01.737545681Z"}
{"log":"\u0009net/http/server.go:2042 +0x44 fp=0xc01c14bb90 sp=0xc01c14bb68 pc=0x7449a4\n","stream":"stderr","time":"2021-03-09T09:26:01.737594445Z"}
{"log":"net/http.(*ServeMux).ServeHTTP(0xc000098940, 0x15a1d80, 0xc01ce44ee0, 0xc01dc53d00)\n","stream":"stderr","time":"2021-03-09T09:26:01.737684824Z"}
{"log":"\u0009net/http/server.go:2417 +0x1ad fp=0xc01c14bbf0 sp=0xc01c14bb90 pc=0x7468cd\n","stream":"stderr","time":"2021-03-09T09:26:01.737730002Z"}
{"log":"net/http.serverHandler.ServeHTTP(0xc00026e380, 0x15a1d80, 0xc01ce44ee0, 0xc01dc53d00)\n","stream":"stderr","time":"2021-03-09T09:26:01.737767403Z"}
{"log":"\u0009net/http/server.go:2843 +0xa3 fp=0xc01c14bc20 sp=0xc01c14bbf0 pc=0x747fa3\n","stream":"stderr","time":"2021-03-09T09:26:01.737814638Z"}
{"log":"net/http.(*conn).serve(0xc026a3d180, 0x15a3600, 0xc02c0972c0)\n","stream":"stderr","time":"2021-03-09T09:26:01.737860943Z"}
{"log":"\u0009net/http/server.go:1925 +0x8ad fp=0xc01c14bfc8 sp=0xc01c14bc20 pc=0x7437ad\n","stream":"stderr","time":"2021-03-09T09:26:01.737901997Z"}
{"log":"runtime.goexit()\n","stream":"stderr","time":"2021-03-09T09:26:01.737936808Z"}
{"log":"\u0009runtime/asm_amd64.s:1374 +0x1 fp=0xc01c14bfd0 sp=0xc01c14bfc8 pc=0x470a81\n","stream":"stderr","time":"2021-03-09T09:26:01.737981537Z"}
{"log":"created by net/http.(*Server).Serve\n","stream":"stderr","time":"2021-03-09T09:26:01.738027458Z"}
{"log":"\u0009net/http/server.go:2969 +0x36c\n","stream":"stderr","time":"2021-03-09T09:26:01.738070249Z"}
{"log":"\n","stream":"stderr","time":"2021-03-09T09:26:01.738103363Z"}
{"log":"goroutine 1 [IO wait, 7 minutes]:\n","stream":"stderr","time":"2021-03-09T09:26:01.738179465Z"}
{"log":"internal/poll.runtime_pollWait(0x7f3744388f18, 0x72, 0x0)\n","stream":"stderr","time":"2021-03-09T09:26:01.738206553Z"}
```

</details>

https://github.com/clarkduvall/hyperloglog/blob/master/hyperloglogplus.go#L150 It seems that the hyperlogplusplus's `tmpset` do not hava the concurrent map lock

**Comment by petethepig** [comment]
That's a bummer. Sorry that happened. Thanks for the report, I'll fix it soon.

**Comment by petethepig** [comment]
Fixed in https://github.com/pyroscope-io/pyroscope/commit/66ad8771696aec72cb754594072c900ce8abdc41

**Comment by scbizu** [comment]
When will  the new release ship to docker hub 🤩

**Comment by petethepig** [comment]
@scbizu I'll release today!
